import {
  normal_badge_locked,
  rare_badge_locked,
  GEN1_unlocked,
  GEN2_unlocked,
  GEN3_unlocked,
  GEN4_unlocked,
  GEN5_unlocked,
  GEN6_unlocked,
  GEN7_unlocked,
  GEN8_unlocked,
  GEN9_unlocked,
  GEN10_unlocked,
  MEN1_unlocked,
  MEN2_unlocked,
  MEN3_unlocked,
  DIS1_unlocked,
  DIS4_unlocked,
  DIS5_unlocked,
  DIS9_unlocked,
  FIE1_unlocked,
  FIE2_unlocked,
  FIE3_unlocked,
  FIE4_unlocked,
  FIE5_unlocked,
  FIE6_unlocked,
  FIE7_unlocked,
  FIE8_unlocked,
  FIE9_unlocked,
  FIE10_unlocked,
  FIE11_unlocked,
  ALC1_unlocked,
  ALC2_unlocked,
  ALC3_unlocked,
  ALC4_unlocked,
  ALC5_unlocked,
  ALC6_unlocked,
  ALC7_unlocked,
  ALC8_unlocked,
  ALC9_unlocked,
  ALC10_unlocked,
  ALC11_unlocked,
  JDM1_unlocked,
  JDM2_unlocked,
  JDM3_unlocked,
  JDM4_unlocked,
  JDM5_unlocked,
  JDM6_unlocked,
  JDM7_unlocked,
  JDM8_unlocked,
  JDM9_unlocked,
  JDM10_unlocked,
  JDM11_unlocked,
  JDM12_unlocked,
  JDM13_unlocked,
  COC1_unlocked,
  COC2_unlocked,
  COC3_unlocked,
  COC4_unlocked,
  COC5_unlocked,
  COC6_unlocked,
  COC7_unlocked,
  COC8_unlocked,
  COC9_unlocked,
  VIA1_unlocked,
  VIA2_unlocked,
  VIA3_unlocked,
  RUT1_unlocked,
  RUT2_unlocked,
  RUT3_unlocked,
  RUT4_unlocked,
  RUT5_unlocked,
  RUT6_unlocked,
  RUT7_unlocked,
  RUT8_unlocked,
  RUT9_unlocked,
  RUT10_unlocked,
  RUT11_unlocked,
  MDL1_unlocked,
  MDL2_unlocked,
  MDL3_unlocked,
  MDL4_unlocked,
  CUL1_unlocked,
  CUL2_unlocked,
  CUL3_unlocked,
  CUL4_unlocked,
  CUL5_unlocked,
  CUL6_unlocked,
  CUL7_unlocked
} from "../assets/img/badge_logos"

export const badges = [{
    id: "GEN1",
    group: "general",
    title: "Creador/a",
    description: "Crea TAG. (Retroactivo)",
    points: "0",
    icon_locked: rare_badge_locked,
    icon_unlocked: GEN1_unlocked,
    type: "rare"
  },
  {
    id: "GEN2",
    group: "general",
    title: "You're Pac, he's Pac, no Pac, none",
    description: "Gana una batalla de gallos.",
    points: "5",
    icon_locked: normal_badge_locked,
    icon_unlocked: GEN2_unlocked,
    type: "normal"
  },
  {
    id: "GEN3",
    group: "general",
    title: "No tienes nada de que avergonzarte",
    description: "Bañarte desnudo/a.",
    points: "10",
    icon_locked: normal_badge_locked,
    icon_unlocked: GEN3_unlocked,
    type: "normal"
  },
  {
    id: "GEN4",
    group: "general",
    title: "Titiritero/a",
    description: "Completar un plan.",
    points: "25",
    icon_locked: rare_badge_locked,
    icon_unlocked: GEN4_unlocked,
    type: "rare"
  },
  {
    id: "GEN5",
    group: "general",
    title: "Swiftie",
    description: "Ser swiftie. (Retroactivo)",
    points: "0",
    icon_locked: rare_badge_locked,
    icon_unlocked: GEN5_unlocked,
    type: "rare"
  },
  {
    id: "GEN6",
    group: "general",
    title: "Ministro/a",
    description: "Proponer un plan no alcohólico y que se llene un coche como mínimo.",
    points: "10",
    icon_locked: normal_badge_locked,
    icon_unlocked: GEN6_unlocked,
    type: "normal"
  },
  {
    id: "GEN7",
    group: "general",
    title: "Filólogo/a",
    description: "Introducir una nueva palabra en ANTX.",
    points: "5",
    icon_locked: normal_badge_locked,
    icon_unlocked: GEN7_unlocked,
    type: "normal"
  },
  {
    id: "GEN8",
    group: "general",
    title: "Real OG",
    description: "Ser real de Sway Dance Floors. (Retroactivo)",
    points: "0",
    icon_locked: rare_badge_locked,
    icon_unlocked: GEN8_unlocked,
    type: "rare"
  },
  {
    id: "GEN9",
    group: "general",
    title: "Paparazzi",
    description: "Hacerse una foto con alguien de cierta relevancia.",
    points: "20",
    icon_locked: rare_badge_locked,
    icon_unlocked: GEN9_unlocked,
    type: "rare"
  },
  {
    id: "GEN10",
    group: "general",
    title: "A mamar, gordo",
    description: "Tener el C1 de Valenciano. (Retroactivo)",
    points: "0",
    icon_locked: rare_badge_locked,
    icon_unlocked: GEN10_unlocked,
    type: "rare"
  },
  {
    id: "MEN1",
    group: "mensual",
    title: "Uno/a de los de 100pre",
    description: "Asistir a todas las mensuales de 2024.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: MEN1_unlocked,
    type: "rare"
  },
  {
    id: "MEN2",
    group: "mensual",
    title: "Cena gratis",
    description: "Gana un mínimo de 10 euros en una mensual.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: MEN2_unlocked,
    type: "rare"
  },
  {
    id: "MEN3",
    group: "mensual",
    title: "Enero",
    description: "Asistir a la mensual de enero.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: MEN3_unlocked,
    type: "normal"
  },
  {
    id: "MEN4",
    group: "mensual",
    title: "Febrero",
    description: "Asistir a la mensual de febrero.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN4_unlocked",
    type: "normal"
  },
  {
    id: "MEN5",
    group: "mensual",
    title: "Marzo",
    description: "Asistir a la mensual de marzo.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN5_unlocked",
    type: "normal"
  },
  {
    id: "MEN6",
    group: "mensual",
    title: "Abril",
    description: "Asistir a la mensual de abril.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN6_unlocked",
    type: "normal"
  },
  {
    id: "MEN7",
    group: "mensual",
    title: "Mayo",
    description: "Asistir a la mensual de mayo.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN7_unlocked",
    type: "normal"
  },
  {
    id: "MEN8",
    group: "mensual",
    title: "Junio",
    description: "Asistir a la mensual de junio.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN8_unlocked",
    type: "normal"
  },
  {
    id: "MEN9",
    group: "mensual",
    title: "Julio",
    description: "Asistir a la mensual de julio.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN9_unlocked",
    type: "normal"
  },
  {
    id: "MEN10",
    group: "mensual",
    title: "Agosto",
    description: "Asistir a la mensual de agosto.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN10_unlocked",
    type: "normal"
  },
  {
    id: "MEN11",
    group: "mensual",
    title: "Septiembre",
    description: "Asistir a la mensual de septiembre.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN11_unlocked",
    type: "normal"
  },
  {
    id: "MEN12",
    group: "mensual",
    title: "Octubre",
    description: "Asistir a la mensual de octubre.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN12_unlocked",
    type: "normal"
  },
  {
    id: "MEN13",
    group: "mensual",
    title: "Noviembre",
    description: "Asistir a la mensual de noviembre.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN13_unlocked",
    type: "normal"
  },
  {
    id: "MEN14",
    group: "mensual",
    title: "Diciembre",
    description: "Asistir a la mensual de diciembre.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN14_unlocked",
    type: "normal"
  },
  {
    id: "DIS1",
    group: "discipulo",
    title: "Maestro/a de ANTX",
    description: "Conviertete en discipulo de todos los miembros de ANTX.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS1_unlocked,
    type: "rare"
  },
  {
    id: "DIS2",
    group: "discipulo",
    title: "Discipulo de Adri Piper",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS2_unlocked",
    type: "rare"
  },
  {
    id: "DIS3",
    group: "discipulo",
    title: "Discipulo de La Gorda",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS3_unlocked",
    type: "rare"
  },
  {
    id: "DIS4",
    group: "discipulo",
    title: "Discipulo de Piudeferro",
    description: "Desaparece en una fiesta y baila con un/a desconocido/a.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS4_unlocked,
    type: "rare"
  },
  {
    id: "DIS5",
    group: "discipulo",
    title: "Discipulo de Leto",
    description: "Ve al cine a solas. Simple.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS5_unlocked,
    type: "rare"
  },
  {
    id: "DIS6",
    group: "discipulo",
    title: "Discipulo de Mimy",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS6_unlocked",
    type: "rare"
  },
  {
    id: "DIS7",
    group: "discipulo",
    title: "Discipulo de Quiqueso",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS7_unlocked",
    type: "rare"
  },
  {
    id: "DIS8",
    group: "discipulo",
    title: "Discipulo de Rodicrack",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS8_unlocked",
    type: "rare"
  },
  {
    id: "DIS9",
    group: "discipulo",
    title: "Discipulo de Nick",
    description: "Coge coche de fiesta o para un viaje largo 5 veces.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS9_unlocked,
    type: "rare"
  },
  {
    id: "DIS10",
    group: "discipulo",
    title: "Discipulo de Visión",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS10_unlocked",
    type: "rare"
  },
  {
    id: "DIS11",
    group: "discipulo",
    title: "Discipulo de Estela",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS11_unlocked",
    type: "rare"
  },
  {
    id: "DIS12",
    group: "discipulo",
    title: "Discipulo de Raymundo",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS12_unlocked",
    type: "rare"
  },
  {
    id: "DIS13",
    group: "discipulo",
    title: "Discipulo de Austin",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS13_unlocked",
    type: "rare"
  },
  {
    id: "DIS14",
    group: "discipulo",
    title: "Discipulo de Ann",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS14_unlocked",
    type: "rare"
  },
  {
    id: "DIS15",
    group: "discipulo",
    title: "Discipulo de MT",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS15_unlocked",
    type: "rare"
  },
  {
    id: "DIS16",
    group: "discipulo",
    title: "Discipulo de Elmen",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS16_unlocked",
    type: "rare"
  },
  {
    id: "DIS17",
    group: "discipulo",
    title: "Discipulo de Deborah",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS17_unlocked",
    type: "rare"
  },
  {
    id: "DIS18",
    group: "discipulo",
    title: "Discipulo de Alberto",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS18_unlocked",
    type: "rare"
  },
  {
    id: "DIS19",
    group: "discipulo",
    title: "Discipulo de Isma",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS19_unlocked",
    type: "rare"
  },
  {
    id: "FIE1",
    group: "fiesta",
    title: "Anfitrión/a",
    description: "Poner casa para cena y lo que surja.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE1_unlocked,
    type: "normal"
  },
  {
    id: "FIE2",
    group: "fiesta",
    title: "Anfitrión/a Máximo/a",
    description: "Organiza una bacanal.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: FIE2_unlocked,
    type: "rare"
  },
  {
    id: "FIE3",
    group: "fiesta",
    title: "Cuenta con mi espada",
    description: "Asiste a una bacanal.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE3_unlocked,
    type: "normal"
  },
  {
    id: "FIE4",
    group: "fiesta",
    title: "Cumplidor/a",
    description: "Acaba una fiesta no antes de las 6 de la mañana.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE4_unlocked,
    type: "normal"
  },
  {
    id: "FIE5",
    group: "fiesta",
    title: "Y nos dieron las 10 y las 11",
    description: "Acaba una fiesta despues de las 10 de la mañana.",
    points: 20,
    icon_locked: rare_badge_locked,
    icon_unlocked: FIE5_unlocked,
    type: "rare"
  },
  {
    id: "FIE6",
    group: "fiesta",
    title: "Defensor/a de la tradición",
    description: "Volver de fiesta andando desde Benaguasil, Marines o más lejos.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE6_unlocked,
    type: "normal"
  },
  {
    id: "FIE7",
    group: "fiesta",
    title: "Juego de espejos",
    description: "Jugar al espejo de fiesta.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE7_unlocked,
    type: "normal"
  },
  {
    id: "FIE8",
    group: "fiesta",
    title: "Sing Star",
    description: "Ir a un karaoke de verdad.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE8_unlocked,
    type: "normal"
  },
  {
    id: "FIE9",
    group: "fiesta",
    title: "¿Conoces a Neil?",
    description: "Jugar a ¿Conoces a Neil? de fiesta.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE9_unlocked,
    type: "normal"
  },
  {
    id: "FIE10",
    group: "fiesta",
    title: "Quiero la hoja de reclamaciones",
    description: "Que te tiren de una fiesta o que no te dejen entrar.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: FIE10_unlocked,
    type: "rare"
  },
  {
    id: "FIE11",
    group: "fiesta",
    title: "Dick pic",
    description: "Hacer fotopolla de fiesta con gente de ANTX.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE11_unlocked,
    type: "normal"
  },
  {
    id: "ALC1",
    group: "alcohol",
    title: "Panxaferro",
    description: "Beber 5 chupitos en una fiesta.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC1_unlocked,
    type: "normal"
  },
  {
    id: "ALC2",
    group: "alcohol",
    title: "Un sorbo normal de Austin",
    description: "Haz un hidalgo de fiesta.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC2_unlocked,
    type: "normal"
  },
  {
    id: "ALC3",
    group: "alcohol",
    title: "Un srb nrml d Astn",
    description: "Haz dos hidalgos de fiesta.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC3_unlocked,
    type: "normal"
  },
  {
    id: "ALC4",
    group: "alcohol",
    title: "Ustn",
    description: "Haz tres hidalgos de fiesta.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: ALC4_unlocked,
    type: "rare"
  },
  {
    id: "ALC5",
    group: "alcohol",
    title: "Estoy to' perdio'",
    description: "Vomita por culpa del alcohol.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC5_unlocked,
    type: "normal"
  },
  {
    id: "ALC6",
    group: "alcohol",
    title: "No sé como llegar",
    description: "Vomita por culpa del alcohol dos veces.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC6_unlocked,
    type: "normal"
  },
  {
    id: "ALC7",
    group: "alcohol",
    title: "Ayuda",
    description: "Vomita por culpa del alcohol tres veces.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: ALC7_unlocked,
    type: "rare"
  },
  {
    id: "ALC8",
    group: "alcohol",
    title: "Socio/a de la Gruta",
    description: "Bebe 25 cervezas.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC8_unlocked,
    type: "normal"
  },
  {
    id: "ALC9",
    group: "alcohol",
    title: "Defensor/a del Goblins",
    description: "Bebe 50 cervezas.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC9_unlocked,
    type: "normal"
  },
  {
    id: "ALC10",
    group: "alcohol",
    title: "¿Como supiste que soy de los guays?",
    description: "Bebe 100 cervezas.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: ALC10_unlocked,
    type: "rare"
  },
  {
    id: "ALC11",
    group: "alcohol",
    title: "Siguiendo los trends",
    description: "Haz el tiktok de 'esto es mi x cubata'.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC11_unlocked,
    type: "normal"
  },
  {
    id: "JDM1",
    group: "juegos_de_mesa",
    title: "El señor de los Jueguillos",
    description: "Gana una partida de cada juego de ANTX.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM1_unlocked,
    type: "rare"
  },
  {
    id: "JDM2",
    group: "juegos_de_mesa",
    title: "Empresario/a",
    description: "Gana una partida de Anatxopoly.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM2_unlocked,
    type: "normal"
  },
  {
    id: "JDM3",
    group: "juegos_de_mesa",
    title: "Tiburón",
    description: "Gana 2 partidas de Anatxopoly.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM3_unlocked,
    type: "normal"
  },
  {
    id: "JDM4",
    group: "juegos_de_mesa",
    title: "Tu propio jefe",
    description: "Gana 3 partidas de Anatxopoly.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM4_unlocked,
    type: "rare"
  },
  {
    id: "JDM5",
    group: "juegos_de_mesa",
    title: "Amigo/a",
    description: "Gana 3 partidas del Quien es Quien.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM5_unlocked,
    type: "normal"
  },
  {
    id: "JDM6",
    group: "juegos_de_mesa",
    title: "Detective",
    description: "Gana 5 partidas del Quien es Quien.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM6_unlocked,
    type: "normal"
  },
  {
    id: "JDM7",
    group: "juegos_de_mesa",
    title: "Oficial de aduanas",
    description: "Gana 10 partidas del Quien es Quien.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM7_unlocked,
    type: "rare"
  },
  {
    id: "JDM8",
    group: "juegos_de_mesa",
    title: "Contacartas",
    description: "Gana 3 partidas en un juego de la Anatxobaraja.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM8_unlocked,
    type: "normal"
  },
  {
    id: "JDM9",
    group: "juegos_de_mesa",
    title: "Dinamó",
    description: "Gana 5 partidas en un juego de la Anatxobaraja.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM9_unlocked,
    type: "normal"
  },
  {
    id: "JDM10",
    group: "juegos_de_mesa",
    title: "Joker",
    description: "Gana 10 partidas en un juego de la Anatxobaraja.",
    points: 10,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM10_unlocked,
    type: "rare"
  },
  {
    id: "JDM11",
    group: "juegos_de_mesa",
    title: "Mimo",
    description: "Gana una partida del juego de los papelitos.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM11_unlocked,
    type: "normal"
  },
  {
    id: "JDM12",
    group: "juegos_de_mesa",
    title: "Intérprete",
    description: "Gana 2 partidas del juego de los papelitos.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM12_unlocked,
    type: "normal"
  },
  {
    id: "JDM13",
    group: "juegos_de_mesa",
    title: "Nominado/a a un oscar",
    description: "Gana 3 partidas del juego de los papelitos.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM13_unlocked,
    type: "rare"
  },
  {
    id: "COC1",
    group: "cochinas",
    title: "Celestino/a",
    description: "Hacer de celestino y que salga bien.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: COC1_unlocked,
    type: "rare"
  },
  {
    id: "COC2",
    group: "cochinas",
    title: "Guarro/a",
    description: "Liate con una persona.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: COC2_unlocked,
    type: "normal"
  },
  {
    id: "COC3",
    group: "cochinas",
    title: "Golfo",
    description: "Liate con dos personas.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: COC3_unlocked,
    type: "normal"
  },
  {
    id: "COC4",
    group: "cochinas",
    title: "Depredador/a",
    description: "Liate con tres personas.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: COC4_unlocked,
    type: "rare"
  },
  {
    id: "COC5",
    group: "cochinas",
    title: "1/99",
    description: "Liate con alguien imposible (se presenta al grupo y se vota).",
    points: 20,
    icon_locked: rare_badge_locked,
    icon_unlocked: COC5_unlocked,
    type: "rare"
  },
  {
    id: "COC6",
    group: "cochinas",
    title: "Los amigos de mis amigos son mis buenos amigos",
    description: "Liate con algun amigo o amiga de alguien de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: COC6_unlocked,
    type: "normal"
  },
  {
    id: "COC7",
    group: "cochinas",
    title: "Domador de milfs / Azote de papis",
    description: "Liate con alguien mucho más mayor.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: COC7_unlocked,
    type: "rare"
  },
  {
    id: "COC8",
    group: "cochinas",
    title: "Asaltacunas",
    description: "No hace falta decir más...",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: COC8_unlocked,
    type: "normal"
  },
  {
    id: "COC9",
    group: "cochinas",
    title: "Leyenda",
    description: "Acabar la temporada con novio/a (Si empiezas la temporada con novio/a, tiene que ser otra persona al final).",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: COC9_unlocked,
    type: "rare"
  },
  {
    id: "VIA1",
    group: "viajes",
    title: "Renovación de ADN",
    description: "Liate con alguien en un viaje.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: VIA1_unlocked,
    type: "normal"
  },
  {
    id: "VIA2",
    group: "viajes",
    title: "Uno no entra simplemente caminando a...",
    description: "Ve de ruta en otro pais.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: VIA2_unlocked,
    type: "normal"
  },
  {
    id: "VIA3",
    group: "viajes",
    title: "Soy ciudadano/a de ANTX",
    description: "Ten problemas con la autoridad en un viaje.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: VIA3_unlocked,
    type: "rare"
  },
  {
    id: "RUT1",
    group: "rutas",
    title: "Dominguero/a",
    description: "Ve de ruta 3 veces con alguien de ANTX.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT1_unlocked,
    type: "normal"
  },
  {
    id: "RUT2",
    group: "rutas",
    title: "Trotamundos",
    description: "Ve de ruta 5 veces con alguien de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT2_unlocked,
    type: "normal"
  },
  {
    id: "RUT3",
    group: "rutas",
    title: "Mi apellido? Durá",
    description: "Ve de ruta 10 veces con alguien de ANTX.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: RUT3_unlocked,
    type: "rare"
  },
  {
    id: "RUT4",
    group: "rutas",
    title: "BRO PERO ANAR AL RIU NO ES UNA RU...",
    description: "Ve al rio.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT4_unlocked,
    type: "normal"
  },
  {
    id: "RUT5",
    group: "rutas",
    title: "Yo quiero ser minero",
    description: "Explora una cueva.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT5_unlocked,
    type: "normal"
  },
  {
    id: "RUT6",
    group: "rutas",
    title: "Romper el pico en el hierro",
    description: "Explora 2 cuevas.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT6_unlocked,
    type: "normal"
  },
  {
    id: "RUT7",
    group: "rutas",
    title: "Como un buen minero",
    description: "Explora 3 cuevas.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: RUT7_unlocked,
    type: "rare"
  },
  {
    id: "RUT8",
    group: "rutas",
    title: "¿Me das un pico?",
    description: "Alcanza una cima",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT8_unlocked,
    type: "normal"
  },
  {
    id: "RUT9",
    group: "rutas",
    title: "Dos cimas como dos...",
    description: "Alcanza dos cimas",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT9_unlocked,
    type: "normal"
  },
  {
    id: "RUT10",
    group: "rutas",
    title: "Las Piernas del Este",
    description: "Alcanza tres cimas",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: RUT10_unlocked,
    type: "rare"
  },
  {
    id: "RUT11",
    group: "rutas",
    title: "Fallo en la realidad",
    description: "Sin ser Carles, organiza una ruta con alguien de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT11_unlocked,
    type: "normal"
  },
  {
    id: "MDL1",
    group: "marines_de_lokiar",
    title: "Discipulo/a",
    description: "Asiste a 3 marines de lokiar.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: MDL1_unlocked,
    type: "normal"
  },
  {
    id: "MDL2",
    group: "marines_de_lokiar",
    title: "Pastor/a",
    description: "Asiste a 5 marines de lokiar.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: MDL2_unlocked,
    type: "normal"
  },
  {
    id: "MDL3",
    group: "marines_de_lokiar",
    title: "Iluminado/a",
    description: "Asiste a 10 marines de lokiar.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: MDL3_unlocked,
    type: "rare"
  },
  {
    id: "MDL4",
    group: "marines_de_lokiar",
    title: "Ministro/a de Cultura de ANTX",
    description: "Propone un tema en un marines de Lokiar y que dure todo el trayecto (ida y vuelta).",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: MDL4_unlocked,
    type: "rare"
  },
  {
    id: "CUL1",
    group: "cultura",
    title: "Leto",
    description: "Ir a la filmoteca una vez.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL1_unlocked,
    type: "normal"
  },
  {
    id: "CUL2",
    group: "cultura",
    title: "Letez",
    description: "Ir a la filmoteca 2 veces.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL2_unlocked,
    type: "normal"
  },
  {
    id: "CUL3",
    group: "cultura",
    title: "Carlos Muñoz Gil",
    description: "Ir a la filmoteca 3 veces.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL3_unlocked,
    type: "normal"
  },
  {
    id: "CUL4",
    group: "cultura",
    title: "Epopeya Anatxiana",
    description: "Ir a la opera.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL4_unlocked,
    type: "normal"
  },
  {
    id: "CUL5",
    group: "cultura",
    title: "Visionspeare",
    description: "Ir a ver una obra de teatro.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL5_unlocked,
    type: "normal"
  },
  {
    id: "CUL6",
    group: "cultura",
    title: "Sabes, yo también tengo algo de científico",
    description: "Ir a un congreso.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL6_unlocked,
    type: "normal"
  },
  {
    id: "CUL7",
    group: "cultura",
    title: "La voz del pueblo",
    description: "Participa en Casa Nostra o La Frontera.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: CUL7_unlocked,
    type: "rare"
  }
]