import {
  normal_badge_locked,
  rare_badge_locked,
  GEN1_unlocked,
  GEN2_unlocked,
  GEN3_unlocked,
  GEN4_unlocked,
  GEN5_unlocked,
  GEN6_unlocked,
  GEN7_unlocked,
  GEN8_unlocked,
  GEN9_unlocked,
  GEN10_unlocked,
  GEN11_unlocked,
  GEN12_unlocked,
  MEN1_unlocked,
  MEN2_unlocked,
  MEN3_unlocked,
  MEN4_unlocked,
  MEN5_unlocked,
  MEN6_unlocked,
  MEN15_unlocked,
  DIS1_unlocked,
  DIS2_unlocked,
  DIS3_unlocked,
  DIS4_unlocked,
  DIS5_unlocked,
  DIS6_unlocked,
  DIS8_unlocked,
  DIS9_unlocked,
  DIS10_unlocked,
  DIS11_unlocked,
  DIS13_unlocked,
  DIS15_unlocked,
  FIE1_unlocked,
  FIE2_unlocked,
  FIE3_unlocked,
  FIE4_unlocked,
  FIE5_unlocked,
  FIE6_unlocked,
  FIE7_unlocked,
  FIE8_unlocked,
  FIE9_unlocked,
  FIE10_unlocked,
  FIE11_unlocked,
  FIE12_unlocked,
  FIE13_unlocked,
  ALC1_unlocked,
  ALC2_unlocked,
  ALC3_unlocked,
  ALC4_unlocked,
  ALC5_unlocked,
  ALC6_unlocked,
  ALC7_unlocked,
  ALC8_unlocked,
  ALC9_unlocked,
  ALC10_unlocked,
  ALC11_unlocked,
  ALC12_unlocked,
  ALC13_unlocked,
  JDM1_unlocked,
  JDM2_unlocked,
  JDM3_unlocked,
  JDM4_unlocked,
  JDM5_unlocked,
  JDM6_unlocked,
  JDM7_unlocked,
  JDM8_unlocked,
  JDM9_unlocked,
  JDM10_unlocked,
  JDM11_unlocked,
  JDM12_unlocked,
  JDM13_unlocked,
  JDM14_unlocked,
  JDM15_unlocked,
  JDM16_unlocked,
  JDM17_unlocked,
  JDM18_unlocked,
  JDM19_unlocked,
  JDM20_unlocked,
  JDM21_unlocked,
  JDM22_unlocked,
  JDM23_unlocked,
  JDM24_unlocked,
  JDM25_unlocked,
  COC1_unlocked,
  COC2_unlocked,
  COC3_unlocked,
  COC4_unlocked,
  COC5_unlocked,
  COC6_unlocked,
  COC7_unlocked,
  COC8_unlocked,
  COC9_unlocked,
  COC10_unlocked,
  COC11_unlocked,
  COC12_unlocked,
  COC13_unlocked,
  VIA1_unlocked,
  VIA2_unlocked,
  VIA3_unlocked,
  VIA4_unlocked,
  VIA5_unlocked,
  VIA6_unlocked,
  VIA7_unlocked,
  VIA8_unlocked,
  VIA9_unlocked,
  RUT1_unlocked,
  RUT2_unlocked,
  RUT3_unlocked,
  RUT4_unlocked,
  RUT5_unlocked,
  RUT6_unlocked,
  RUT7_unlocked,
  RUT8_unlocked,
  RUT9_unlocked,
  RUT10_unlocked,
  RUT11_unlocked,
  RUT12_unlocked,
  MDL1_unlocked,
  MDL2_unlocked,
  MDL3_unlocked,
  MDL4_unlocked,
  MDL5_unlocked,
  CUL1_unlocked,
  CUL2_unlocked,
  CUL3_unlocked,
  CUL4_unlocked,
  CUL5_unlocked,
  CUL6_unlocked,
  CUL7_unlocked,
  CUL8_unlocked,
  CUL9_unlocked,
  CUL10_unlocked,
  CUL11_unlocked,
  CUL12_unlocked,
  CUL13_unlocked,
  CUL14_unlocked,
  CUL15_unlocked,
  CUL16_unlocked,
  CUL17_unlocked,
  DEP1_unlocked,
  DEP2_unlocked,
  DEP3_unlocked,
  DEP4_unlocked,
  DEP5_unlocked,
  DEP6_unlocked,
  DEP7_unlocked,
  DEP8_unlocked,
  DEP9_unlocked,
  DEP10_unlocked,
  DEP11_unlocked,
  DEP12_unlocked,
  DEP13_unlocked,
  DEP14_unlocked,
  DEP15_unlocked,
  DEP16_unlocked,
  DEP17_unlocked,
  LEC1_unlocked,
  LEC2_unlocked,
  LEC3_unlocked,
  LEC4_unlocked,
  LEC5_unlocked,
  LEC6_unlocked,
  LEC7_unlocked,
  EV_CAR1_unlocked,
  EV_CAR2_unlocked,
  EV_CAR3_unlocked,
  EV_CAR4_unlocked,
  EV_CAR5_unlocked,
  EV_FAL1_unlocked,
  EV_FAL2_unlocked,
  EV_FAL3_unlocked,
  EV_FAL4_unlocked,
  EV_FAL5_unlocked,
  EV_FAL6_unlocked,
  EV_FAL7_unlocked,
  EV_FAL8_unlocked,
  EV_FAL9_unlocked,
  EV_FAL10_unlocked,
  EV_FAL11_unlocked,
  EV_FAL12_unlocked,
  EV_FAL13_unlocked,
  EV_FAL14_unlocked,
  EV_FAL15_unlocked,
  EV_FAL16_unlocked,
  EV_SANVI1_unlocked,
  EV_SANVI2_unlocked,
  EV_SANVI3_unlocked,
  EV_SANVI4_unlocked,
  EV_SANVI5_unlocked,
  EV_SANVI6_unlocked,
  EV_SANVI7_unlocked,
  EV_SANVI8_unlocked,
  EV_SANVI9_unlocked,
  EV_SANVI10_unlocked
} from "../assets/img/badge_logos"

import {
  update1,
  update2,
  //update3,
  //update4,
  carnavales,
  fallas,
  sanvi
} from "../assets/img/update_symbols"

export const badges = [{
    id: "GEN1",
    group: "general",
    title: "Creador/a",
    description: "Crea TAG. (Retroactivo)",
    points: 0,
    icon_locked: rare_badge_locked,
    icon_unlocked: GEN1_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "GEN2",
    group: "general",
    title: "You're Pac, he's Pac, no Pac, none",
    description: "Gana una batalla de gallos.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: GEN2_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "GEN3",
    group: "general",
    title: "No tienes nada de que avergonzarte",
    description: "Bañarte desnudo/a.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: GEN3_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "GEN4",
    group: "general",
    title: "Titiritero/a",
    description: "Completar un plan.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: GEN4_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "GEN5",
    group: "general",
    title: "Swiftie",
    description: "Ser swiftie. (Retroactivo)",
    points: 0,
    icon_locked: rare_badge_locked,
    icon_unlocked: GEN5_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "GEN6",
    group: "general",
    title: "Ministro/a",
    description: "Proponer un plan no alcohólico y que se llene un coche como mínimo.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: GEN6_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "GEN7",
    group: "general",
    title: "Filólogo/a",
    description: "Introducir una nueva palabra en ANTX.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: GEN7_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "GEN8",
    group: "general",
    title: "Real OG",
    description: "Ser real de Sway Dance Floors. (Retroactivo)",
    points: 0,
    icon_locked: rare_badge_locked,
    icon_unlocked: GEN8_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "GEN9",
    group: "general",
    title: "Paparazzi",
    description: "Hacerse una foto con alguien de cierta relevancia.",
    points: 20,
    icon_locked: rare_badge_locked,
    icon_unlocked: GEN9_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "GEN10",
    group: "general",
    title: "A mamar, gordo",
    description: "Tener el C1 de Valenciano. (Retroactivo)",
    points: 0,
    icon_locked: rare_badge_locked,
    icon_unlocked: GEN10_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "GEN11",
    group: "general",
    title: "Yo estuve allí...",
    description: "Haber asistido a la presentación de THE ANATXO GAMES. (Retroactivo)",
    points: 0,
    icon_locked: rare_badge_locked,
    icon_unlocked: GEN11_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "GEN12",
    group: "general",
    title: "Leto, opina de los guays",
    description: "Haz un #AnatxoRespon.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: GEN12_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "MEN1",
    group: "mensual",
    title: "Uno/a de los de 100pre",
    description: "Asiste a todas las mensuales de 2024.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: MEN1_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN2",
    group: "mensual",
    title: "Cena gratis",
    description: "Gana un mínimo de 10 euros en una mensual.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: MEN2_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN3",
    group: "mensual",
    title: "Enero",
    description: "Asiste a la mensual de enero.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: MEN3_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN4",
    group: "mensual",
    title: "Febrero",
    description: "Asiste a la mensual de febrero.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: MEN4_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN5",
    group: "mensual",
    title: "Marzo",
    description: "Asiste a la mensual de marzo.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: MEN5_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN6",
    group: "mensual",
    title: "Abril",
    description: "Asiste a la mensual de abril.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: MEN6_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN7",
    group: "mensual",
    title: "Mayo",
    description: "Asiste a la mensual de mayo.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN7_unlocked",
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN8",
    group: "mensual",
    title: "Junio",
    description: "Asiste a la mensual de junio.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN8_unlocked",
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN9",
    group: "mensual",
    title: "Julio",
    description: "Asiste a la mensual de julio.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN9_unlocked",
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN10",
    group: "mensual",
    title: "Agosto",
    description: "Asiste a la mensual de agosto.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN10_unlocked",
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN11",
    group: "mensual",
    title: "Septiembre",
    description: "Asiste a la mensual de septiembre.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN11_unlocked",
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN12",
    group: "mensual",
    title: "Octubre",
    description: "Asiste a la mensual de octubre.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN12_unlocked",
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN13",
    group: "mensual",
    title: "Noviembre",
    description: "Asiste a la mensual de noviembre.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN13_unlocked",
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN14",
    group: "mensual",
    title: "Diciembre",
    description: "Asiste a la mensual de diciembre.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "MEN14_unlocked",
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MEN15",
    group: "mensual",
    title: "Un clanero más",
    description: "Asiste a 6 mensuales seguidas.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: MEN15_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "DIS1",
    group: "discipulo",
    title: "Maestro/a de ANTX",
    description: "Conviertete en discipulo de todos los miembros de ANTX.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS1_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS2",
    group: "discipulo",
    title: "Discipulo de Adri Piper",
    description: "Bebe 3,3L de cerveza en 5 horas.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS2_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS3",
    group: "discipulo",
    title: "Discipulo de La Gorda",
    description: "Viaja a dos paises.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS3_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS4",
    group: "discipulo",
    title: "Discipulo de Piudeferro",
    description: "Baila con un/a desconocido/a de fiesta.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS4_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS5",
    group: "discipulo",
    title: "Discipulo de Leto",
    description: "Ve al cine o a la filmoteca a solas. Simple.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS5_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS6",
    group: "discipulo",
    title: "Discipulo de Mimy",
    description: "Bebe 3 chupitos de Jägermeister en una noche.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS6_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS7",
    group: "discipulo",
    title: "Discipulo de Quiqueso",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS7_unlocked",
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS8",
    group: "discipulo",
    title: "Discipulo de Sergio",
    description: "Ve a Barcelona y sal de fiesta con Sergi.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS8_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS9",
    group: "discipulo",
    title: "Discipulo de Nick",
    description: "Coge coche de fiesta o para un viaje largo 5 veces.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS9_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS10",
    group: "discipulo",
    title: "Discipulo de Visión",
    description: "Hazte el ciego de fiesta. (Palo y gafas incluidas)",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS10_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS11",
    group: "discipulo",
    title: "Discipulo de Inshallah",
    description: "Comprar algo en una sexshop que vayas a utilizar (En una tienda física).",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS11_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS12",
    group: "discipulo",
    title: "Discipulo de Raymundo",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS12_unlocked",
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS13",
    group: "discipulo",
    title: "Discipulo de Austin",
    description: "Hacerte una foto delante de 3 estadios de futbol de primera división.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS13_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS14",
    group: "discipulo",
    title: "Discipulo de Ann",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS14_unlocked",
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS15",
    group: "discipulo",
    title: "Discipulo de MT",
    description: "Llora de fiesta.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DIS15_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS16",
    group: "discipulo",
    title: "Discipulo de Elmen",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS16_unlocked",
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS17",
    group: "discipulo",
    title: "Discipulo de Deborah",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS17_unlocked",
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS18",
    group: "discipulo",
    title: "Discipulo de Bertinho Gaucho",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS18_unlocked",
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "DIS19",
    group: "discipulo",
    title: "Discipulo de Ismatthew",
    description: "???",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: "DIS19_unlocked",
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "FIE1",
    group: "fiesta",
    title: "Anfitrión/a",
    description: "Poner casa para cena y lo que surja.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE1_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "FIE2",
    group: "fiesta",
    title: "Anfitrión/a Máximo/a",
    description: "Organiza una bacanal.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: FIE2_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "FIE3",
    group: "fiesta",
    title: "Cuenta con mi espada",
    description: "Asiste a una bacanal.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE3_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "FIE4",
    group: "fiesta",
    title: "Cumplidor/a",
    description: "Acaba una fiesta no antes de las 6 de la mañana.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE4_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "FIE5",
    group: "fiesta",
    title: "Y nos dieron las 10 y las 11",
    description: "Acaba una fiesta despues de las 10 de la mañana.",
    points: 20,
    icon_locked: rare_badge_locked,
    icon_unlocked: FIE5_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "FIE6",
    group: "fiesta",
    title: "Defensor/a de la tradición",
    description: "Volver de fiesta andando desde Benaguasil, Marines o más lejos.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE6_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "FIE7",
    group: "fiesta",
    title: "Juego de espejos",
    description: "Jugar al espejo de fiesta.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE7_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "FIE8",
    group: "fiesta",
    title: "Sing Star",
    description: "Ir a un karaoke de verdad.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE8_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "FIE9",
    group: "fiesta",
    title: "¿Conoces a Neil?",
    description: "Jugar a ¿Conoces a Neil? de fiesta.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE9_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "FIE10",
    group: "fiesta",
    title: "Quiero la hoja de reclamaciones",
    description: "Que te tiren de una fiesta o que no te dejen entrar.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: FIE10_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "FIE11",
    group: "fiesta",
    title: "Dick pic",
    description: "Hacer fotopolla de fiesta con gente de ANTX.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE11_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "FIE12",
    group: "fiesta",
    title: "Solo por Les Castizos",
    description: "Ve a un festival.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: FIE12_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "FIE13",
    group: "fiesta",
    title: "Una noche legendaria",
    description: "Ve de bar en bar por Lliria hasta que cierre el último del pueblo con gente de ANTX.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: FIE13_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "ALC1",
    group: "alcohol",
    title: "Panxaferro",
    description: "Beber 5 chupitos en una fiesta.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC1_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "ALC2",
    group: "alcohol",
    title: "Un sorbo normal de Austin",
    description: "Haz un hidalgo de fiesta.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC2_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "ALC3",
    group: "alcohol",
    title: "Un srb nrml d Astn",
    description: "Haz dos hidalgos de fiesta.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC3_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "ALC4",
    group: "alcohol",
    title: "Ustn",
    description: "Haz tres hidalgos de fiesta.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: ALC4_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "ALC5",
    group: "alcohol",
    title: "Estoy to' perdio'",
    description: "Vomita por culpa del alcohol en una fiesta.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC5_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "ALC6",
    group: "alcohol",
    title: "No sé como llegar",
    description: "Vomita por culpa del alcohol dos veces en una fiesta.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC6_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "ALC7",
    group: "alcohol",
    title: "Ayuda",
    description: "Vomita por culpa del alcohol tres veces en una fiesta.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: ALC7_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "ALC8",
    group: "alcohol",
    title: "Socio/a de la Gruta",
    description: "Bebe 25 cervezas.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC8_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "ALC9",
    group: "alcohol",
    title: "Defensor/a del Goblins",
    description: "Bebe 50 cervezas.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC9_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "ALC10",
    group: "alcohol",
    title: "¿Como supiste que soy de los guays?",
    description: "Bebe 100 cervezas.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: ALC10_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "ALC11",
    group: "alcohol",
    title: "Siguiendo los trends",
    description: "Haz el tiktok de 'esto es mi x cubata'.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: ALC11_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "ALC12",
    group: "alcohol",
    title: "Game. Over.",
    description: "Coma etílico (No vayais a por esta aposta por favor).",
    points: 20,
    icon_locked: rare_badge_locked,
    icon_unlocked: ALC12_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "ALC13",
    group: "alcohol",
    title: "Alcohólico",
    description: "Bebe 200 cervezas.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: ALC13_unlocked,
    type: "rare",
    update: 2,
    updateIcon: update2
  },
  {
    id: "JDM1",
    group: "juegos",
    title: "El señor de los Jueguillos",
    description: "Gana una partida de cada juego de ANTX.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM1_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "JDM2",
    group: "juegos",
    title: "Empresario/a",
    description: "Gana una partida de Anatxopoly.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM2_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "JDM3",
    group: "juegos",
    title: "Tiburón",
    description: "Gana 2 partidas de Anatxopoly.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM3_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "JDM4",
    group: "juegos",
    title: "Tu propio jefe",
    description: "Gana 3 partidas de Anatxopoly.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM4_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "JDM5",
    group: "juegos",
    title: "Amigo/a",
    description: "Gana 3 partidas del AnatxoQuien.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM5_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "JDM6",
    group: "juegos",
    title: "Detective",
    description: "Gana 5 partidas del AnatxoQuien.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM6_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "JDM7",
    group: "juegos",
    title: "Oficial de aduanas",
    description: "Gana 10 partidas del AnatxoQuien.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM7_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "JDM8",
    group: "juegos",
    title: "Contacartas",
    description: "Gana 3 partidas en un juego de la Anatxobaraja.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM8_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "JDM9",
    group: "juegos",
    title: "Dinamó",
    description: "Gana 5 partidas en un juego de la Anatxobaraja.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM9_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "JDM10",
    group: "juegos",
    title: "Joker",
    description: "Gana 10 partidas en un juego de la Anatxobaraja.",
    points: 10,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM10_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "JDM11",
    group: "juegos",
    title: "Mimo",
    description: "Gana una partida del juego de los papelitos.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM11_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "JDM12",
    group: "juegos",
    title: "Intérprete",
    description: "Gana 2 partidas del juego de los papelitos.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM12_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "JDM13",
    group: "juegos",
    title: "Nominado/a a un oscar",
    description: "Gana 3 partidas del juego de los papelitos.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM13_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "JDM14",
    group: "juegos",
    title: "Uno más entre los dioses",
    description: "Crea un nuevo juego de mesa de ANTX.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM14_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "JDM15",
    group: "juegos",
    title: "It's me! Ismatthew!",
    description: "Gana un campeonato de Mario Kart contra gente de ANTX. (Un torneo es un Grand Prix de 4 personas)",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM15_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "JDM16",
    group: "juegos",
    title: "¿Vale tu amistad 10 puntos?",
    description: "Gana una partida del Wii Party o Mario Party contra gente de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM16_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "JDM17",
    group: "juegos",
    title: "Chico/a del coro",
    description: "Gana 3 partidas de Sing Star.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM17_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "JDM18",
    group: "juegos",
    title: "Mariangeles",
    description: "Gana 5 partidas de Sing Star.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM18_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "JDM19",
    group: "juegos",
    title: "Ganador/a de OT",
    description: "Gana 10 partidas de Sing Star.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM19_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "JDM20",
    group: "juegos",
    title: "Fiebre de Sabado Noche",
    description: "Gana 3 partidas de Just Dance.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM20_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "JDM21",
    group: "juegos",
    title: "Casti",
    description: "Gana 5 partidas de Just Dance.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM21_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "JDM22",
    group: "juegos",
    title: "Destructor de Caderas",
    description: "Gana 10 partidas de Just Dance.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM22_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "JDM23",
    group: "juegos",
    title: "Fotógrafo",
    description: "Gana 3 partidas de Photo Roulette contra 3 personas de ANTX.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM23_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "JDM24",
    group: "juegos",
    title: "Espía",
    description: "Gana 5 partidas de Photo Roulette contra 3 personas de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: JDM24_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "JDM25",
    group: "juegos",
    title: "Bro me miras el tlf?",
    description: "Gana 10 partidas de Photo Roulette contra 3 personas de ANTX.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: JDM25_unlocked,
    type: "rare",
    update: 2,
    updateIcon: update2
  },
  {
    id: "COC1",
    group: "cochinas",
    title: "Celestino/a",
    description: "Haz de celestino y que salga bien.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: COC1_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "COC2",
    group: "cochinas",
    title: "Guarro/a",
    description: "Liate con una persona.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: COC2_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "COC3",
    group: "cochinas",
    title: "Golfo",
    description: "Liate con dos personas.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: COC3_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "COC4",
    group: "cochinas",
    title: "Depredador/a",
    description: "Liate con tres personas.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: COC4_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "COC5",
    group: "cochinas",
    title: "1/99",
    description: "Liate con alguien imposible (se presenta al grupo y se vota).",
    points: 20,
    icon_locked: rare_badge_locked,
    icon_unlocked: COC5_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "COC6",
    group: "cochinas",
    title: "Los amigos de mis amigos son mis buenos amigos",
    description: "Liate con algun amigo o amiga de alguien de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: COC6_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "COC7",
    group: "cochinas",
    title: "Domador de milfs / Azote de papis",
    description: "Liate con alguien mucho más mayor.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: COC7_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "COC8",
    group: "cochinas",
    title: "Asaltacunas",
    description: "No hace falta decir más...",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: COC8_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "COC9",
    group: "cochinas",
    title: "Leyenda",
    description: "Acaba la temporada con novio/a (Si empiezas la temporada con novio/a, tiene que ser otra persona al final).",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: COC9_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "COC10",
    group: "cochinas",
    title: "Año par",
    description: "Liate con tu ex.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: COC10_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "COC11",
    group: "cochinas",
    title: "Ozil",
    description: "Asiste a que algun colega se lie.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: COC11_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "COC12",
    group: "cochinas",
    title: "¿Sabes que Leto sabe mucho de cine?",
    description: "Ensalzar a un colega mientras está con un/a tio/a.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: COC12_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "COC13",
    group: "cochinas",
    title: "Para vosotros jugadores",
    description: "Presenta gente nueva a ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: COC13_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "VIA1",
    group: "viajes",
    title: "Renovación de ADN",
    description: "Liate con alguien que hayas conocido en un viaje.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: VIA1_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "VIA2",
    group: "viajes",
    title: "Uno no entra simplemente caminando a...",
    description: "Ve de ruta en otro pais.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: VIA2_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "VIA3",
    group: "viajes",
    title: "Soy ciudadano/a de ANTX",
    description: "Ten problemas con la autoridad en un viaje.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: VIA3_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "VIA4",
    group: "viajes",
    title: "Sugar Daddy",
    description: "Paga una compra de más de 20 euros en un viaje con gente de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: VIA4_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "VIA5",
    group: "viajes",
    title: "Casti no cuenta",
    description: "Visita un castillo de viaje.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: VIA5_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "VIA6",
    group: "viajes",
    title: "Prohibido vomitar en iglesias",
    description: "Visita una iglesia de viaje.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: VIA6_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "VIA7",
    group: "viajes",
    title: "20 minutes Sergi adventure",
    description: "Visita y realiza una actividad en otra comunidad autonoma.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: VIA7_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "VIA8",
    group: "viajes",
    title: "Sicue",
    description: "Visita y realiza una actividad en otras 2 comunidades autonomas.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: VIA8_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "VIA9",
    group: "viajes",
    title: "Uandelas",
    description: "Visita y realiza una actividad en otras 3 comunidades autonomas.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: VIA9_unlocked,
    type: "rare",
    update: 2,
    updateIcon: update2
  },
  {
    id: "RUT1",
    group: "rutas",
    title: "Dominguero/a",
    description: "Ve de ruta con alguien de ANTX.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT1_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "RUT2",
    group: "rutas",
    title: "Trotamundos",
    description: "Ve de ruta 3 veces con alguien de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT2_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "RUT3",
    group: "rutas",
    title: "Mi apellido? Durá",
    description: "Ve de ruta 5 veces con alguien de ANTX.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: RUT3_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "RUT4",
    group: "rutas",
    title: "BRO PERO ANAR AL RIU NO ES UNA RU...",
    description: "Ve al rio con alguien de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT4_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "RUT5",
    group: "rutas",
    title: "Yo quiero ser minero",
    description: "Explora una cueva.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT5_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "RUT6",
    group: "rutas",
    title: "Romper el pico en el hierro",
    description: "Explora 2 cuevas.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT6_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "RUT7",
    group: "rutas",
    title: "Como un buen minero",
    description: "Explora 3 cuevas.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: RUT7_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "RUT8",
    group: "rutas",
    title: "¿Un piquito?",
    description: "Alcanza una cima",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT8_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "RUT9",
    group: "rutas",
    title: "Dos cimas como dos...",
    description: "Alcanza dos cimas",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT9_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "RUT10",
    group: "rutas",
    title: "Las Piernas del Este",
    description: "Alcanza tres cimas",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: RUT10_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "RUT11",
    group: "rutas",
    title: "Fallo en la realidad",
    description: "Sin ser Carles, organiza una ruta con alguien de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: RUT11_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "RUT12",
    group: "rutas",
    title: "La única vez que MT lloró con razón",
    description: "Escala el Puig Campana con alguien de ANTX.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: RUT12_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "MDL1",
    group: "marines_de_lokiar",
    title: "Discipulo/a",
    description: "Asiste a un Marines de Lokiar.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: MDL1_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MDL2",
    group: "marines_de_lokiar",
    title: "Pastor/a",
    description: "Asiste a 3 Marines de Lokiar.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: MDL2_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "MDL3",
    group: "marines_de_lokiar",
    title: "Iluminado/a",
    description: "Asiste a 5 Marines de Lokiar.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: MDL3_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "MDL4",
    group: "marines_de_lokiar",
    title: "Ministro/a de Cultura de ANTX",
    description: "Propone un tema en un Marines de Lokiar y que dure todo el trayecto (ida y vuelta).",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: MDL4_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "MDL5",
    group: "marines_de_lokiar",
    title: "Olocau de Lokiar",
    description: "No seremos capaces, no?",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: MDL5_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "CUL1",
    group: "cultura",
    title: "Leto",
    description: "Ir a la filmoteca una vez.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL1_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "CUL2",
    group: "cultura",
    title: "Letez",
    description: "Ir a la filmoteca 2 veces.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL2_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "CUL3",
    group: "cultura",
    title: "Carlos Muñoz Gil",
    description: "Ir a la filmoteca 3 veces.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL3_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "CUL4",
    group: "cultura",
    title: "Epopeya Anatxiana",
    description: "Ir a la opera.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL4_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "CUL5",
    group: "cultura",
    title: "Visionspeare",
    description: "Ir a ver una obra de teatro.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL5_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "CUL6",
    group: "cultura",
    title: "Sabes, yo también tengo algo de científico",
    description: "Ir a un congreso.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL6_unlocked,
    type: "normal",
    update: 0,
    updateIcon: null
  },
  {
    id: "CUL7",
    group: "cultura",
    title: "La voz del pueblo",
    description: "Participa en Casa Nostra o La Frontera.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: CUL7_unlocked,
    type: "rare",
    update: 0,
    updateIcon: null
  },
  {
    id: "CUL8",
    group: "cultura",
    title: "Estela Estilos",
    description: "Ir a un concierto.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL8_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "CUL9",
    group: "cultura",
    title: "¿A las 7? Minimo a las 2 en la cola",
    description: "Ir a dos conciertos.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL9_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "CUL10",
    group: "cultura",
    title: "Vendí mi casa por una entrada de la Taylor",
    description: "Ir a tres conciertos.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL10_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "CUL11",
    group: "cultura",
    title: "Estimado Sr. Jones",
    description: "Ir a un museo.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL11_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "CUL12",
    group: "cultura",
    title: "I'm a man of wealth and taste",
    description: "Ir a dos museos.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL12_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "CUL13",
    group: "cultura",
    title: "DEBERÍA ESTAR EN UN MUSEO",
    description: "Ir a tres museos.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: CUL13_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "CUL14",
    group: "cultura",
    title: "¿Tu eres de la Unió o del Clarín?",
    description: "Ir a un concierto de música clásica.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL14_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "CUL15",
    group: "cultura",
    title: "Tio",
    description: "Ir al cine con gente de ANTX una vez.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL15_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "CUL16",
    group: "cultura",
    title: "¿Más chapas de cine?",
    description: "Ir al cine con gente de ANTX dos veces.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: CUL16_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "CUL17",
    group: "cultura",
    title: "¿ENSERIO?",
    description: "Ir al cine con gente de ANTX tres veces.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: CUL17_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "DEP1",
    group: "deporte",
    title: "Hooligan",
    description: "Asiste a un partido con alguien de ANTX.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: DEP1_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "DEP2",
    group: "deporte",
    title: "Abonat al Llíria UD",
    description: "Asiste a dos partidos con alguien de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: DEP2_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "DEP3",
    group: "deporte",
    title: "MJ",
    description: "Asiste a tres partidos con alguien de ANTX.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DEP3_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "DEP4",
    group: "deporte",
    title: "Vaporeon",
    description: "Ves hasta la boya en la playa.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DEP4_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "DEP5",
    group: "deporte",
    title: "Oh capitán, mi capitán",
    description: "Convoca y organiza una pachanga con gente de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: DEP5_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "DEP6",
    group: "deporte",
    title: "No puedo tengo furbo",
    description: "Participa en una pachanga de ANTX.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: DEP6_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "DEP7",
    group: "deporte",
    title: "La banda del patio",
    description: "Participa en dos pachangas de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: DEP7_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "DEP8",
    group: "deporte",
    title: "Oliver y Benji",
    description: "Participa en tres pachangas de ANTX.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: DEP8_unlocked,
    type: "rare",
    update: 1,
    updateIcon: update1
  },
  {
    id: "DEP9",
    group: "deporte",
    title: "Saps que Carles ha fet una mitja marató?",
    description: "Apuntate y realiza a una carrera conjunta.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: DEP9_unlocked,
    type: "normal",
    update: 1,
    updateIcon: update1
  },
  {
    id: "DEP10",
    group: "deporte",
    title: "Barras barras",
    description: "Ir un día a hacer barras.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: DEP10_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "DEP11",
    group: "deporte",
    title: "Pensalas",
    description: "Ir 3 días a hacer barras.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: DEP11_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "DEP12",
    group: "deporte",
    title: "Frases cantadas por un MC",
    description: "Ir 5 días a hacer barras.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: DEP12_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "DEP13",
    group: "deporte",
    title: "Maestro de la Fuerza",
    description: "Haz 5 dominadas seguidas.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: DEP13_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "DEP14",
    group: "deporte",
    title: "Maestro del Equilibrio",
    description: "Haz 10 fondos seguidos.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: DEP14_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "DEP15",
    group: "deporte",
    title: "Maestro del Impulso",
    description: "Haz 20 flexiones seguidas.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: DEP15_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "DEP16",
    group: "deporte",
    title: "Maestro de Corridas",
    description: "Ir a correr todos los días durante una semana, o durante un mes entero mínimo tres dies a la semana.",
    points: 20,
    icon_locked: rare_badge_locked,
    icon_unlocked: DEP16_unlocked,
    type: "rare",
    update: 2,
    updateIcon: update2
  },
  {
    id: "DEP17",
    group: "deporte",
    title: "Nadie habla sobre el Club de la lucha",
    description: "Asistix a una pelea de boxeo legal... o ilegal.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: DEP17_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC1",
    group: "lectura",
    title: "El club de los poetas muertos",
    description: "Asiste a todos los clubes de lectura.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: LEC1_unlocked,
    type: "rare",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC2",
    group: "lectura",
    title: "Una mentirosa más",
    description: "Asiste a 5 clubes de lectura seguidos.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: LEC2_unlocked,
    type: "rare",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC3",
    group: "lectura",
    title: "Rata de biblioteca",
    description: "Ir 5 veces a la biblioteca.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: LEC3_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC4",
    group: "lectura",
    title: "Opositor",
    description: "Ir 10 veces a la biblioteca.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: LEC4_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC5",
    group: "lectura",
    title: "Dios del conocimiento",
    description: "Ir 15 veces a la biblioteca.",
    points: 20,
    icon_locked: rare_badge_locked,
    icon_unlocked: LEC5_unlocked,
    type: "rare",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC6",
    group: "lectura",
    title: "El terror de los inmaterialistas",
    description: "Ir a alguna feria del libro.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: LEC6_unlocked,
    type: "rare",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC7",
    group: "lectura",
    title: "Marzo: Romance",
    description: "Asiste al club de lectura de marzo.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: LEC7_unlocked,
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC8",
    group: "lectura",
    title: "Abril: Fantasía",
    description: "Asiste al club de lectura de abril.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "LEC8_unlocked",
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC9",
    group: "lectura",
    title: "Mayo: ???",
    description: "Asiste al club de lectura de mayo.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "LEC9_unlocked",
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC10",
    group: "lectura",
    title: "Junio: ???",
    description: "Asiste al club de lectura de junio.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "LEC10_unlocked",
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC11",
    group: "lectura",
    title: "Julio: ???",
    description: "Asiste al club de lectura de julio.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "LEC11_unlocked",
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC12",
    group: "lectura",
    title: "Agosto: ???",
    description: "Asiste al club de lectura de agosto.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "LEC12_unlocked",
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC13",
    group: "lectura",
    title: "Septiembre: ???",
    description: "Asiste al club de lectura de septiembre.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "LEC13_unlocked",
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC14",
    group: "lectura",
    title: "Octubre: ???",
    description: "Asiste al club de lectura de octubre.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "LEC14_unlocked",
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC15",
    group: "lectura",
    title: "Noviembre: ???",
    description: "Asiste al club de lectura de noviembre.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "LEC15_unlocked",
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "LEC16",
    group: "lectura",
    title: "Diciembre: ???",
    description: "Asiste al club de lectura de diciembre.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: "LEC16_unlocked",
    type: "normal",
    update: 2,
    updateIcon: update2
  },
  {
    id: "EV_CAR1",
    group: "carnavales",
    title: "Carnaval, carnavaaaaaal",
    description: "Asiste a los carnavales de Villar.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_CAR1_unlocked,
    type: "normal",
    update: "carnavales",
    updateIcon: carnavales
  },
  {
    id: "EV_CAR2",
    group: "carnavales",
    title: "Curas, astronautas y...",
    description: "Ve disfrazado de la misma temática que al menos 2 miembros de ANTX.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_CAR2_unlocked,
    type: "normal",
    update: "carnavales",
    updateIcon: carnavales
  },
  {
    id: "EV_CAR3",
    group: "carnavales",
    title: "Control de alcoholemia asegurado",
    description: "Pon tu coche para carnavales.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: EV_CAR3_unlocked,
    type: "rare",
    update: "carnavales",
    updateIcon: carnavales
  },
  {
    id: "EV_CAR4",
    group: "carnavales",
    title: "Yo nunca me he liado con un alien de toy story",
    description: "Triunfa en carnavales de Villar.",
    points: 20,
    icon_locked: rare_badge_locked,
    icon_unlocked: EV_CAR4_unlocked,
    type: "rare",
    update: "carnavales",
    updateIcon: carnavales
  },
  {
    id: "EV_CAR5",
    group: "carnavales",
    title: "Carnaval te quiero",
    description: "Aguanta carnavales de Villar hasta que acabe la fiesta... del todo.",
    points: 25,
    icon_locked: rare_badge_locked,
    icon_unlocked: EV_CAR5_unlocked,
    type: "rare",
    update: "carnavales",
    updateIcon: carnavales
  },
  {
    id: "EV_FAL1",
    group: "fallas",
    title: "JA ESTEM EN FALLES",
    description: "Ir a la crida.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: EV_FAL1_unlocked,
    type: "rare",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL2",
    group: "fallas",
    title: "Secanetista",
    description: "Ir a la falla de Ann.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_FAL2_unlocked,
    type: "normal",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL3",
    group: "fallas",
    title: "Extramurista",
    description: "Ir a la falla de Mimy.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_FAL3_unlocked,
    type: "normal",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL4",
    group: "fallas",
    title: "Liga de casales no alineados",
    description: "Ir de fiesta a un casal que no sea de Ann, Mimy o Carla y Belén.",
    points: 15,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_FAL4_unlocked,
    type: "normal",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL5",
    group: "fallas",
    title: "Pum",
    description: "Ir a una mascletá.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_FAL5_unlocked,
    type: "normal",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL6",
    group: "fallas",
    title: "Puuum",
    description: "Ir a dos mascletás.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_FAL6_unlocked,
    type: "normal",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL7",
    group: "fallas",
    title: "PUUPUUUPUUPUUPUUUUM",
    description: "Ir a tres mascletás.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_FAL7_unlocked,
    type: "normal",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL8",
    group: "fallas",
    title: "Carlos, Guille y los demás ",
    description: "Ir con los amigos de QM7.",
    points: 20,
    icon_locked: rare_badge_locked,
    icon_unlocked: EV_FAL8_unlocked,
    type: "rare",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL9",
    group: "fallas",
    title: "Falla de colesterol ",
    description: "Comprar y comer unos churros con chocolate.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_FAL9_unlocked,
    type: "normal",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL10",
    group: "fallas",
    title: "Despertà-tor",
    description: "Tirar un petardo tocho tochísimo.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_FAL10_unlocked,
    type: "normal",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL11",
    group: "fallas",
    title: "Cheperudeta Enjoyer",
    description: "Ir a la ofrenda.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_FAL11_unlocked,
    type: "normal",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL12",
    group: "fallas",
    title: "Un navajazo bajo la luz dels castells",
    description: "Ir a la nit del foc.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: EV_FAL12_unlocked,
    type: "rare",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL13",
    group: "fallas",
    title: "Tio que rollo",
    description: "Haz fotos a 5 fallas distintas.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_FAL13_unlocked,
    type: "normal",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL14",
    group: "fallas",
    title: "No et fan mal els peus? ",
    description: "Haz fotos a 10 fallas distintas.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_FAL14_unlocked,
    type: "normal",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL15",
    group: "fallas",
    title: "VULL TORNAR A CASA",
    description: "Haz fotos a 15 fallas distintas.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_FAL15_unlocked,
    type: "normal",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_FAL16",
    group: "fallas",
    title: "Feel the caloret",
    description: "Ver quemar una falla.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: EV_FAL16_unlocked,
    type: "rare",
    update: "fallas",
    updateIcon: fallas
  },
  {
    id: "EV_SANVI1",
    group: "sanvi",
    title: "El millor día del any",
    description: "Asiste a las paellas de San Vicente.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_SANVI1_unlocked,
    type: "normal",
    update: "sanvi",
    updateIcon: sanvi
  },
  {
    id: "EV_SANVI2",
    group: "sanvi",
    title: "BOICOT A 72",
    description: "Lleva la camiseta de ANTX el dia de las paellas.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_SANVI2_unlocked,
    type: "normal",
    update: "sanvi",
    updateIcon: sanvi
  },
  {
    id: "EV_SANVI3",
    group: "sanvi",
    title: "Carmen \"Carmy\" Berzatto",
    description: "Haz una de las paellas.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: EV_SANVI3_unlocked,
    type: "rare",
    update: "sanvi",
    updateIcon: sanvi
  },
  {
    id: "EV_SANVI4",
    group: "sanvi",
    title: "Sergi no va a tener esta ni de coña",
    description: "Ayuda al cocinero o a los cocineros. (Los cocineros decidirán quien ha ayudado de verdad)",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_SANVI4_unlocked,
    type: "normal",
    update: "sanvi",
    updateIcon: sanvi
  },
  {
    id: "EV_SANVI5",
    group: "sanvi",
    title: "I paell?",
    description: "Prueba de otras 3 paellas",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_SANVI5_unlocked,
    type: "normal",
    update: "sanvi",
    updateIcon: sanvi
  },
  {
    id: "EV_SANVI6",
    group: "sanvi",
    title: "L'aigua de la vida",
    description: "Prueba el alcohol de otros 3 grupos.",
    points: 10,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_SANVI6_unlocked,
    type: "normal",
    update: "sanvi",
    updateIcon: sanvi
  },
  {
    id: "EV_SANVI7",
    group: "sanvi",
    title: "Leto no va a tener esta ni de coña",
    description: "Participa en lavar las paellas.",
    points: 15,
    icon_locked: rare_badge_locked,
    icon_unlocked: EV_SANVI7_unlocked,
    type: "rare",
    update: "sanvi",
    updateIcon: sanvi
  },
  {
    id: "EV_SANVI8",
    group: "sanvi",
    title: "Real hasta la muerte oiste baby brrrrrrrrr",
    description: "Asiste a la cena post-paellas.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_SANVI8_unlocked,
    type: "normal",
    update: "sanvi",
    updateIcon: sanvi
  },
  {
    id: "EV_SANVI9",
    group: "sanvi",
    title: "SANT VICENT, SANT VICENT, SANT VICENT!",
    description: "Asiste al almuerzo en el parque San Vicente, el dia de San Vicente.",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_SANVI9_unlocked,
    type: "normal",
    update: "sanvi",
    updateIcon: sanvi
  },
  {
    id: "EV_SANVI10",
    group: "sanvi",
    title: "Pasteleria de Marivi Enjoyer",
    description: "La mañana del 8 de abril de 2024, realiza una compra de una o varias unidades de comida en la pasteleria de Marivi (Carrer del Pla de l'Arc, 75, 46160 Llíria, Valencia) para luego ingerirla(s) por via oral, masticando frecuentemente, mientras estás ubicado en el parque de San Vicente (C. 5, 25, Km. 2,5, 46160 Llíria, Valencia).",
    points: 5,
    icon_locked: normal_badge_locked,
    icon_unlocked: EV_SANVI10_unlocked,
    type: "normal",
    update: "sanvi",
    updateIcon: sanvi
  }
]

export const categories = [{
    title: "Lectura",
    category: "lectura",
    emoji: "react@emojify-72",
    color: "[#c19770]",
    borderColor: "border-[#c19770]",
    bgColor: "bg-[#c19770]",
    newCategory: true
  },
  {
    title: "General",
    category: "general",
    emoji: "react@emojify-1293",
    color: "secondary",
    borderColor: "border-secondary",
    bgColor: "bg-secondary",
    newCategory: false
  },
  {
    title: "Mensual",
    category: "mensual",
    emoji: "react@emojify-737",
    color: "[#0078AC]",
    borderColor: "border-[#0078AC]",
    bgColor: "bg-[#0078AC]",
    newCategory: false
  },
  {
    title: "Discipulo",
    category: "discipulo",
    emoji: "react@emojify-1161",
    color: "[#c7bc28]",
    borderColor: "border-[#c7bc28]",
    bgColor: "bg-[#c7bc28]",
    newCategory: false
  },
  {
    title: "Deporte",
    category: "deporte",
    emoji: "react@emojify-1064",
    color: "[#039942]",
    borderColor: "border-[#039942]",
    bgColor: "bg-[#039942]",
    newCategory: false
  },
  {
    title: "Fiesta",
    category: "fiesta",
    emoji: "react@emojify-1044",
    color: "purple-500",
    borderColor: "border-purple-500",
    bgColor: "bg-purple-500",
    newCategory: false
  },
  {
    title: "Alcohol",
    category: "alcohol",
    emoji: "react@emojify-802",
    color: "[#7f1734]",
    borderColor: "border-[#7f1734]",
    bgColor: "bg-[#7f1734]",
    newCategory: false
  },
  {
    title: "Juegos",
    category: "juegos",
    emoji: "react@emojify-1101",
    color: "white",
    borderColor: "border-white",
    bgColor: "bg-white",
    newCategory: false
  },
  {
    title: "Viajes",
    category: "viajes",
    emoji: "react@emojify-946",
    color: "[#073590]",
    borderColor: "border-[#073590]",
    bgColor: "bg-[#073590]",
    newCategory: false
  },
  {
    title: "Cochinadas",
    category: "cochinas",
    emoji: "react@emojify-62",
    color: "[#e03f3f]",
    borderColor: "border-[#e03f3f]",
    bgColor: "bg-[#e03f3f]",
    newCategory: false
  },
  {
    title: "Rutas",
    category: "rutas",
    emoji: "react@emojify-873",
    color: "[#023020]",
    borderColor: "border-[#023020]",
    bgColor: "bg-[#023020]",
    newCategory: false
  },
  {
    title: "Marines de Lokiar",
    category: "marines_de_lokiar",
    emoji: "react@emojify-161",
    color: "[#FF7F50]",
    borderColor: "border-[#FF7F50]",
    bgColor: "bg-[#FF7F50]",
    newCategory: false
  },
  {
    title: "Cultura",
    category: "cultura",
    emoji: "react@emojify-1218",
    color: "blue-300",
    borderColor: "border-blue-300",
    bgColor: "bg-blue-300",
    newCategory: false
  }
]

export const events = [{
  title: "Carnavales",
  category: "carnavales",
  emoji: "react@emojify-1115",
  color: "[#FF7F50]",
  borderColor: "border-[#FF7F50]",
  bgColor: "bg-[#FF7F50]",
  eventTimeStart: new Date(2024, 1, 10, 12),
  eventTimeEnd: new Date(2024, 1, 11, 12)
},
{
  title: "Fallas",
  category: "fallas",
  emoji: "react@emojify-1034",
  color: "[#880808]",
  borderColor: "border-[#880808]",
  bgColor: "bg-[#880808]",
  eventTimeStart: new Date(2024, 1, 25, 18),
  eventTimeEnd: new Date(2024, 2, 20, 6)
},
{
  title: "Paelles de Sant Vicent",
  category: "sanvi",
  emoji: "react@emojify-747",
  color: "[#348a38]",
  borderColor: "border-[#348a38]",
  bgColor: "bg-[#348a38]",
  eventTimeStart: new Date(2024, 3, 7, 6),
  eventTimeEnd: new Date(2024, 3, 8, 18)
},
]

/* Color codes 
General: #7EC46D
Mensual: #0078AC
Discipulo: #c7bc28
Fiesta: #A855F7
Alcohol: #7f1734
Juegos: #FFFFFF
Viajes: #073590
Cochinadas: #e03f3f
Rutas: #023020
Marines: #FF7F50
Cultura: #93C5FD
Deporte: #039942
Lectura: #c19770

Carnavales: #FF7F50
Fallas: #880808
Paellas de San Vicente: #348a38
*/